name: mycroft-core
version: 19.8.7
summary:  79 char long summary
description:  a longer description for the snap
base: core18
confinement: devmode # use "strict" to enforce system access only via declared interfaces
build-packages: [python3-dev, python3-setuptools, libtool, libffi-dev, libssl-dev, autoconf, bison, libglib2.0-dev, portaudio19-dev, mpg123, python-psutil, speech-dispatcher, swig, libfann-dev]
parts:
  mycroft-core:
    plugin: python
    python-version: python3
    source: https://github.com/MycroftAI/mycroft-core.git
    source-type: git
    source-branch: master
    build-packages: [python-psutil, python-setuptools]
    stage-packages: [speech-dispatcher, libfann2, libjack0, libportaudio2, libsndio6.1, git]

apps:
  messagebus:
    plugs: [home, network, network-bind]
    environment:
      LANGUAGE: "C.UTF-8"
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
    command: python3 -m mycroft.messagebus.service
    daemon: simple
  skills-client:
    plugs: [home]
    environment:
      LANGUAGE: "C.UTF-8"
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
    command: python3 -m mycroft.messagbus.skills
    daemon: simple
  speech-client:
    plugs: [home, network, pulseaudio]
    environment:
      LANGUAGE: "C.UTF-8"
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
    command: python3 -m mycroft.client.speech
    daemon: simple
  cli-client:
    environment:
      LANGUAGE: "C.UTF-8"
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
    command: python3 -m mycroft.client.text
